/** Every image the app ships. React Native needs a literal require() per
 *  asset, so this map is generated rather than written by hand. */
export const ART = {
  'band0': require('../assets/art/band0.webp'),
  'band1': require('../assets/art/band1.webp'),
  'band2': require('../assets/art/band2.webp'),
  'band3': require('../assets/art/band3.webp'),
  'band4': require('../assets/art/band4.webp'),
  'crust0': require('../assets/art/crust0.webp'),
  'crust1': require('../assets/art/crust1.webp'),
  'crust2': require('../assets/art/crust2.webp'),
  'crust3': require('../assets/art/crust3.webp'),
  'crust4': require('../assets/art/crust4.webp'),
  'crust5': require('../assets/art/crust5.webp'),
  'den-fen': require('../assets/art/den-fen.webp'),
  'den-gemmi': require('../assets/art/den-gemmi.webp'),
  'den-nix': require('../assets/art/den-nix.webp'),
  'den-orin': require('../assets/art/den-orin.webp'),
  'den-pyrin': require('../assets/art/den-pyrin.webp'),
  'egg-fen': require('../assets/art/egg-fen.webp'),
  'egg-gemmi': require('../assets/art/egg-gemmi.webp'),
  'egg-nix': require('../assets/art/egg-nix.webp'),
  'egg-orin': require('../assets/art/egg-orin.webp'),
  'egg-pyrin': require('../assets/art/egg-pyrin.webp'),
  'eggopen-fen': require('../assets/art/eggopen-fen.webp'),
  'eggopen-gemmi': require('../assets/art/eggopen-gemmi.webp'),
  'eggopen-nix': require('../assets/art/eggopen-nix.webp'),
  'eggopen-orin': require('../assets/art/eggopen-orin.webp'),
  'eggopen-pyrin': require('../assets/art/eggopen-pyrin.webp'),
  'fen': require('../assets/art/fen.webp'),
  'fen-cheer': require('../assets/art/fen-cheer.webp'),
  'fen-eat': require('../assets/art/fen-eat.webp'),
  'fen-happy': require('../assets/art/fen-happy.webp'),
  'fen-hungry': require('../assets/art/fen-hungry.webp'),
  'fen-idle': require('../assets/art/fen-idle.webp'),
  'fen-sleep': require('../assets/art/fen-sleep.webp'),
  'gemmi': require('../assets/art/gemmi.webp'),
  'gemmi-cheer': require('../assets/art/gemmi-cheer.webp'),
  'gemmi-eat': require('../assets/art/gemmi-eat.webp'),
  'gemmi-happy': require('../assets/art/gemmi-happy.webp'),
  'gemmi-hungry': require('../assets/art/gemmi-hungry.webp'),
  'gemmi-idle': require('../assets/art/gemmi-idle.webp'),
  'gemmi-sleep': require('../assets/art/gemmi-sleep.webp'),
  'glow': require('../assets/art/glow.webp'),
  'home': require('../assets/art/home.webp'),
  'nix': require('../assets/art/nix.webp'),
  'nix-cheer': require('../assets/art/nix-cheer.webp'),
  'nix-eat': require('../assets/art/nix-eat.webp'),
  'nix-happy': require('../assets/art/nix-happy.webp'),
  'nix-hungry': require('../assets/art/nix-hungry.webp'),
  'nix-idle': require('../assets/art/nix-idle.webp'),
  'nix-sleep': require('../assets/art/nix-sleep.webp'),
  'orin': require('../assets/art/orin.webp'),
  'orin-cheer': require('../assets/art/orin-cheer.webp'),
  'orin-eat': require('../assets/art/orin-eat.webp'),
  'orin-happy': require('../assets/art/orin-happy.webp'),
  'orin-hungry': require('../assets/art/orin-hungry.webp'),
  'orin-idle': require('../assets/art/orin-idle.webp'),
  'orin-scene': require('../assets/art/orin-scene.webp'),
  'orin-sleep': require('../assets/art/orin-sleep.webp'),
  'pyrin': require('../assets/art/pyrin.webp'),
  'pyrin-cheer': require('../assets/art/pyrin-cheer.webp'),
  'pyrin-eat': require('../assets/art/pyrin-eat.webp'),
  'pyrin-happy': require('../assets/art/pyrin-happy.webp'),
  'pyrin-hungry': require('../assets/art/pyrin-hungry.webp'),
  'pyrin-idle': require('../assets/art/pyrin-idle.webp'),
  'pyrin-sleep': require('../assets/art/pyrin-sleep.webp'),
  'sil-fen': require('../assets/art/sil-fen.webp'),
  'sil-gemmi': require('../assets/art/sil-gemmi.webp'),
  'sil-nix': require('../assets/art/sil-nix.webp'),
  'sil-orin': require('../assets/art/sil-orin.webp'),
  'sil-pyrin': require('../assets/art/sil-pyrin.webp'),
  'sovereign': require('../assets/art/sovereign.webp'),
  'sovereign-scene': require('../assets/art/sovereign-scene.webp'),
  'strata': require('../assets/art/strata.webp'),
} as const;

export type ArtKey = keyof typeof ART;
/** Falls back to the idle frame, so a missing pose can never crash a screen. */
export const pose = (species: string, p: string) =>
  (ART as any)[`${species}-${p}`] ?? (ART as any)[`${species}-idle`] ?? ART['orin-idle'];
export const den = (species: string) => (ART as any)[`den-${species}`] ?? ART['den-orin'];
/** The buried crust, thickest first. Each strike takes one layer off. */
export const CRUST = [ART.crust0, ART.crust1, ART.crust2, ART.crust3, ART.crust4, ART.crust5];
